default: &default
 host: localhost
 adapter: postgresql
 encoding: UTF8
 username: superuser
 timeout: 5000
 reaping_frequency: 30
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: db_development
  password: password


test:
  <<: *default
  database: db_test
  password: password


production:
  <<: *default
  database: db_production
  password: password

